### ISSUE TITLE
Logs folder still uses old `~/.sanescansrv/logs`

### ISSUE THREAD

**Issue by CoolCat467** [CoolCat467/Scanner-Server#83]
The server logs are still being created in `~/.sanescansrv/logs`, that doesn't follow XDG base directory specification!

**Comment by coderhs** [comment]
@CoolCat467 I am looking at the code and tested the app. it seems the error logs are going to the `~/.sanescansrv/logs` and server logs are going based on XDG base directory specification.

by error i mean the exception for the try block. 

```
[Sane Scanner Webserver] [Wed Oct  2 18:26:10 2024] [INFO] Shutting down from keyboard interrupt
[Sane Scanner Webserver] [Wed Oct  2 18:27:06 2024] [INFO] Shutting down from keyboard interrupt
```

The reason why its doing that is because the log method expects the log directory to be passed along with it, and if not passed its defaulting to  `~/.sanescansrv/logs` 

```py
def log(message: str, level: int = 1, log_dir: str | None = None) -> None:
```

This can be fixed at the method call like so:

```py
log("Shutting down from keyboard interrupt", 1, logs_path)
```

PS: In case I understood the issue wrong, kindly point me in the correct direction.

**Comment by CoolCat467** [comment]
Thank you so much, that fixed it!

**Comment by coderhs** [comment]
:-D I should have mentioned it as trying to do for `hacktoberfest` so that I could send the PR for this to get credit. Its okay, on to the next.

**Comment by CoolCat467** [comment]
Ah, sorry about that
